(source gnu)
(source melpa)

(depends-on "cask")

;;Theme
(depends-on "spacegray-theme")
(depends-on "niflheim-theme")
(depends-on "zenburn-theme")
(depends-on "solarized-theme")

(depends-on "expand-region")
(depends-on "ace-jump-mode")
(depends-on "auto-complete")
(depends-on "flx-ido")
(depends-on "yasnippet")
(depends-on "projectile")
(depends-on "helm-projectile")
(depends-on "php-mode")
(depends-on "js2-mode")
(depends-on "emmet-mode")
(depends-on "scss-mode")
(depends-on "web-mode")
(depends-on "drupal-mode")
(depends-on "smooth-scrolling")
(depends-on "neotree")
(depends-on "visual-fill-column")
(depends-on "org-trello")
(depends-on "emmet-mode")
(depends-on "move-text")